### ISSUE TITLE
Missing icons.png

### ISSUE THREAD

**Issue by trolleycrash** [jacobscarter/angular-feedback#1]
Hi there,

the CSS references a sprite file called `icons.png`, but that file isn't in the repo anywhere (that my addled mind can find, anyhow).

Am I missing something?

**Comment by earthquakesan** [comment]
It is indeed missing, you can find it here and just copy to dist/ folder

http://jacobscarter.github.io/angular-feedback/bower_components/angular-send-feedback/dist/icons.png

**Comment by trolleycrash** [comment]
Indeed, I found it one the demo site and downloaded it directly. However, getting it into the repository would mean that I could deploy it with bower, using stock CSS.

**Comment by jacobscarter** [comment]
@trolleycrash submitted a merge request and this is fixed, thanks!
