### ISSUE TITLE
Unable to parse HTTP body- error occurred :: 'Error: invalid json'

### ISSUE THREAD

**Issue by aman-gautam** [jacobscarter/angular-feedback#14]
Great work with the library! 

The library is sending url-encoded data to the server together with `Content-Type: application/json` which is breaking the server.

**Comment by jacobscarter** [comment]
@aman-gautam I am updating several things tomorrow so that I can use this is a project of mine, I will look into it them

**Comment by jacobscarter** [comment]
Bug being fixed in release 1.2.0, should be available now
